version: '3.8'

volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:latest
    volumes:
    - postgres_data:/var/lib/postgresql/data
    env_file:
    - .env
  web:
    image: noctu13/yamdb:v1.0f
    build: .
    restart: always
    volumes:
      - static_data:/code/static
      - media_data:/code/media
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/usr/share/nginx/html/static:ro
      - media_data:/usr/share/nginx/html/media:ro
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - web
