version: '3.8'

volumes:
  postgres_data:
  static_data:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    image: noctu13/yamdb:v1.0f
    restart: always
    volumes:
      - static_data:/code/static
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_data:/usr/share/nginx/html/static:ro
    ports:
      - 80:80
    depends_on:
      - web
